### ISSUE TITLE
ply library is now at 3.10, 3.9 does not download from pypi any more

### ISSUE THREAD

**Issue by proffalken** [virtuald/pyhcl#33]
Please can we update the dependencies to reflect the new library?

When I install the latest version of ply manually, I get the following output when try and install pyhcl:

```
pip install --index-url=http://pypi.python.org/simple/ pyhcl
Downloading/unpacking pyhcl
  Downloading pyhcl-0.3.8.tar.gz
  Running setup.py egg_info for package pyhcl
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/workspace/my_terraform_job/.venv/build/pyhcl/setup.py", line 96, in <module>
        "Topic :: Text Processing"
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/workspace/my_terraform_job/.venv/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/workspace/my_terraform_job/.venv/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/workspace/my_terraform_job/.venv/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (ply 3.10 (/workspace/my_terraform_job/.venv/lib/python2.7/site-packages), Requirement.parse('ply==3.9'))
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/workspace/my_terraform_job/.venv/build/pyhcl/setup.py", line 96, in <module>

    "Topic :: Text Processing"

  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup

    _setup_distribution = dist = klass(attrs)

  File "/workspace/my_terraform_job/.venv/lib/python2.7/site-packages/setuptools/dist.py", line 265, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/workspace/my_terraform_job/.venv/lib/python2.7/site-packages/setuptools/dist.py", line 289, in fetch_build_eggs

    parse_requirements(requires), installer=self.fetch_build_egg

  File "/workspace/my_terraform_job/.venv/lib/python2.7/site-packages/pkg_resources.py", line 630, in resolve

    raise VersionConflict(dist,req) # XXX put more info here

pkg_resources.VersionConflict: (ply 3.10 (/workspace/my_terraform_job/.venv/lib/python2.7/site-packages), Requirement.parse('ply==3.9'))

----------------------------------------
Cleaning up...
```

**Comment by virtuald** [comment]
It's not clear to me why the other version didn't work for you -- installing 3.9 in a virtualenv works fine for me. However, I'm fine with upgrading.

**Comment by proffalken** [comment]
Thanks :)
