### ISSUE TITLE
Unable to pip install; No module named 'ply'

### ISSUE THREAD

**Issue by scbunn** [virtuald/pyhcl#39]
This started happened today

```
❯ pip install pyhcl
Collecting pyhcl
  Using cached pyhcl-0.3.10.tar.gz
Collecting ply==3.10 (from pyhcl)
  Using cached ply-3.10.tar.gz
Building wheels for collected packages: pyhcl, ply
  Running setup.py bdist_wheel for pyhcl ... error
  Complete output from command /usr/local/opt/python/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/f4/rdfz0fk96tggm7k6lm9_10n00000gn/T/pip-build-gx2kk83q/pyhcl/setup.
py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/f4/rdfz0fk96tggm7k6lm9_10n00000gn/T/tmp
_zczlpg5pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  Generating parse table...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/f4/rdfz0fk96tggm7k6lm9_10n00000gn/T/pip-build-gx2kk83q/pyhcl/setup.py", line 96, in <module>
      "Topic :: Text Processing"
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/f4/rdfz0fk96tggm7k6lm9_10n00000gn/T/pip-build-gx2kk83q/pyhcl/setup.py", line 37, in run
      self.execute(_pre_install, (), msg="Generating parse table...")
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 335, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/util.py", line 301, in execute
      func(*args)
    File "/private/var/folders/f4/rdfz0fk96tggm7k6lm9_10n00000gn/T/pip-build-gx2kk83q/pyhcl/setup.py", line 30, in _pre_install
      import hcl
    File "/private/var/folders/f4/rdfz0fk96tggm7k6lm9_10n00000gn/T/pip-build-gx2kk83q/pyhcl/src/hcl/__init__.py", line 1, in <module>
      from .api import dumps, load, loads
    File "/private/var/folders/f4/rdfz0fk96tggm7k6lm9_10n00000gn/T/pip-build-gx2kk83q/pyhcl/src/hcl/api.py", line 3, in <module>
      from .parser import HclParser
    File "/private/var/folders/f4/rdfz0fk96tggm7k6lm9_10n00000gn/T/pip-build-gx2kk83q/pyhcl/src/hcl/parser.py", line 5, in <module>
      from .lexer import Lexer
    File "/private/var/folders/f4/rdfz0fk96tggm7k6lm9_10n00000gn/T/pip-build-gx2kk83q/pyhcl/src/hcl/lexer.py", line 3, in <module>
      import ply.lex as lex
  ModuleNotFoundError: No module named 'ply'

  ----------------------------------------
  Failed building wheel for pyhcl
  Running setup.py clean for pyhcl
  Running setup.py bdist_wheel for ply ... done
  Stored in directory: /Users/scbunn/Library/Caches/pip/wheels/ad/dd/ad/8ce1991a7b380dfe23d6cc81a4de5c2775bc728b5a0a7721aa
Successfully built ply
Failed to build pyhcl
Installing collected packages: ply, pyhcl
  Running setup.py install for pyhcl ... done
Successfully installed ply-3.10 pyhcl-0.3.10

```

It looks like pyhcl gets installed; but it causes my jobs to fail due to the error.

**Comment by scbunn** [comment]
```
pip uninstall ply; pip uninstall pyhcl; pip install ply; pip install pyhcl 
```

That seems to resolve the issue.

**Comment by antonagestam** [comment]
This error still happens on initial install. Sequentially running `pip install ply` then `pip install pyhcl` works. It looks like this is due to `pyhcl` is depending on `ply` at setup-time. This issues should probably be reopened until this is really resolved?

**Comment by pdonorio** [comment]
Hello! I get this error too in my pip install of Delgan/loguru, which depends on this.

**Comment by virtuald** [comment]
I noticed recently that another library (pcpp) has started vendoring ply, since ply is no longer distributing via pypi. That might make sense for pyhcl.
